name       : libytnef
version    : "2.0"
release    : 1
source     :
    - https://github.com/Yeraze/ytnef/archive/refs/tags/v2.0.tar.gz : bb12f34572de89e4825fce98d2d235d93cd34b2c41fed0074ebfa89af9e724a9
license    : GPL-2.0-or-later
component  : desktop.library
summary    : TNEF Stream Reader library
description: |
    TNEF Stream Reader library (decodes winmail.dat)
builddeps  :
    - perl
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
